spring:
  application:
    name: SmartVault
    version: 0.0.1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS
app:
  datasource:
    url: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0&sslmode=require

